# import = ["~/.config/alacritty/dracula.toml"]
import = ["~/.config/alacritty/github_dark_default.toml"]
# import = ["~/.config/alacritty/github_dark.toml"]
# import = ["~/.config/alacritty/github_dark_dimmed.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
opacity = 0.94
# opacity = 1
decorations = "None"
[window.padding]
x = 10
y = 2


